/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCBASEDS_DATA_H_RPCGEN
#define _RPCBASEDS_DATA_H_RPCGEN

#if 0
typedef unsigned int u_int;
#endif

typedef int HRESULT;

struct RPCRES_LONG {
	HRESULT result;
	unsigned int data;
};
typedef struct RPCRES_LONG RPCRES_LONG;

struct USB_DEVICE_CONFIG_INFO {
	HRESULT ret;
	unsigned int usb_ai_samplerate;
	unsigned int usb_ai_format;
	unsigned int usb_ai_chnum;
};
typedef struct USB_DEVICE_CONFIG_INFO USB_DEVICE_CONFIG_INFO;

struct RPC_CONNECTION {
	unsigned int srcInstanceID;
	unsigned int srcPinID;
	unsigned int desInstanceID;
	unsigned int desPinID;
	unsigned int mediaType;
};
typedef struct RPC_CONNECTION RPC_CONNECTION;

struct RPC_SEND_LONG {
	unsigned int instanceID;
	unsigned int pinID;
	unsigned int data;
};
typedef struct RPC_SEND_LONG RPC_SEND_LONG;

#endif /* !_RPCBASEDS_DATA_H_RPCGEN */
