/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VIDEORPC_AGENT_H_RPCGEN
#define _VIDEORPC_AGENT_H_RPCGEN

#include <RPCstruct.h>

#include "VideoRPC_Agent_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <RPCBaseDS.h>
#include <VideoRPCBaseDS.h>
#include <AudioRPCBaseDS.h>
#include <AudioRPC_Agent.h>

#define VIDEO_AGENT 202
#define VERSION 0

struct REG_STRUCT * VIDEO_AGENT_0_register(struct REG_STRUCT *rnode);

#if defined(__STDC__) || defined(__cplusplus)
#define VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg 5
extern  HRESULT * VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg_0(VIDEO_RPC_DEC_JPEG_INFO *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg_0_svc(VIDEO_RPC_DEC_JPEG_INFO *, RPC_STRUCT *, HRESULT *);

#else /* K&R C */
#define VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg 5
extern  HRESULT * VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg_0();
extern  HRESULT * VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg_0_svc();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_VIDEO_RPC_TRANSITION_EFFECT_CTRL (XDR *, VIDEO_RPC_TRANSITION_EFFECT_CTRL*);

#else /* K&R C */
extern bool_t xdr_VIDEO_RPC_TRANSITION_EFFECT_CTRL ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VIDEORPC_AGENT_H_RPCGEN */
