/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VIDEORPCBASEDS_H_RPCGEN
#define _VIDEORPCBASEDS_H_RPCGEN

#include <RPCstruct.h>

#include "VideoRPCBaseDS_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <rpc_common.h>
#include <AudioRPCBaseDS.h>
#include <AudioRPC_Agent.h>
#include <AudioRPC_System.h>

#ifdef __cplusplus
}
#endif

#endif /* !_VIDEORPCBASEDS_H_RPCGEN */
