/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VIDEORPCBASEDS_DATA_H_RPCGEN
#define _VIDEORPCBASEDS_DATA_H_RPCGEN

#include <rpc_common.h>
#include <AudioRPCBaseDS.h>
#include <AudioRPC_Agent.h>
#include <AudioRPC_System.h>

#endif /* !_VIDEORPCBASEDS_DATA_H_RPCGEN */
